select * from SistemaInterfaces
go




delete from UsuariosAgenciasMenuPrincipal
DELETE FROM SistemaMenuPrincipal

INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(1, NULL, 'TSMIArchivo', 'Archivo', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(2, 1, 'TSMIRespaldo', 'Respaldo', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(3, 2, 'TSMIImportar', 'Importar', 'M', '', 'TSBImportar', 'Importar', '', 'Importar', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(4, 2, 'TSMIExportar', 'Exportar', 'M', '', 'TSBExportar', 'Exportar', '', 'Exportar', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(5, 2, 'TSMIBitacora', 'Bitacora', 'M', '', 'TSBBitacora', 'Bitacora', '', 'Bitacora', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(6, 1, 'TSMISistema', 'Sistema', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(7, 6, 'TSMIAgencias', 'Agencias', 'M', '', 'TSBAgencias', 'Agencias', '', 'Agencias', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(8, 6, 'TSMIUsuarios', 'Usuarios', 'M', '', 'TSBUsuarios', 'Usuarios', '', 'Usuarios', 18)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(9, 6, 'TSMIPreferencias', 'Preferencias', 'M', '', 'TSBPreferencias', 'Preferencias', '', 'Preferencias', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(10, 1, 'TSMISeparador1', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(11, 1, 'TSMISalir', 'Salir', 'M', '', 'TSBSalir', 'Salir', '', 'Salir', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(12, NULL, 'TSMIAVer', 'Ver', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(13, NULL, 'TSMIRegistros', 'Registro', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(14, 13, 'TSMIPersonas', 'Personas', 'M', '', 'TSBPersonas', 'Personas', '', 'Personas', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(15, 13, 'TSMISeparador2', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(16, 13, 'TSMIProveedores', 'Proveedores', 'M', '', 'TSBProveedores', 'Proveedores', '', 'Proveedores',16)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(17, 13, 'TSMISeparador3', '-', 'S', '', NULL, 'Proveedores', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(18, 13, 'TSMIClientes', 'Clientes', 'M', '', 'TSBClientes', 'Clientes', '', 'Clientes',4)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(19, 13, 'TSMISeparador4', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(20, 13, 'TSMIProductos', 'Productos', 'M', '', 'TSBProductos', 'Productos', '', 'Productos',11)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(21, 13, 'TSMISeparador5', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(22, 13, 'TSMICotizacionMonedas', 'Cotizaciones', 'M', '', 'TSBCotizacionMonedas', 'Cotizaciones', '', 'CotizacionMonedas', 9)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(23, 13, 'TSMISeparador6', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(24, 13, 'TSMIPlanCuentas', 'Plan de Cuentas', 'M', '', 'TSBPlanCuentas', 'Plan de Cuentas', '', 'PlanCuentass', 27)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(25, NULL, 'TSMITransacciones', 'Transacciones', 'M', '', 'TSBTransacciones', 'Transacciones', '', 'Transacciones', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(26, 25, 'TSMICompras', 'Compras', 'M','', 'TSBCompras', 'Compras', '', 'Compras', 2) 
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(27, 25, 'TSMIPagoComprasProductos', 'Pago de Compras Productos', 'M','', 'TSBPagoComprasProductos', '', '',  'PagoComprasProducto', 44)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(28, 25, 'TSMIRecepcionComprasProductos', 'Recepción de Compras Productos', 'M','', 'TSBRecepcionComprasProductos', '', '',  'RecepcionComprasProductos', 43)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(29, 25, 'TSMIDevolucionesCompras', 'Devoluciones compras', 'M','', 'TSBDevolucionesCompras', 'Devoluciones compras', '', 'DevolucionesCompras', 23)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(30, 25, 'TSMICuentasPorPagar', 'Cuentas por pagar', 'M', '', 'TSBCuentasPorPagar', 'Cuentas por pagar', '', 'CuentasPorPagar', 20)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(31, 25, 'TSMISeparador7', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(32, 25, 'TSMIVentas', 'Ventas', 'M','', 'TSBVentas', '', '',  'Ventas', 17)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(33, 25, 'TSMIPagoVentasProductos', 'Pago de Ventas Productos', 'M','', 'TSBPagoVentasProductos', '', '',  'PagoVentasProducto', 22)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(34, 25, 'TSMIEntregaVentasProductos', 'Entrega de Ventas Productos', 'M','', 'TSBEntregaVentasProductos', '', '',  'EntregaVentasProductos', 21)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(35, 25, 'TSMIDevolucionesVentas', 'Devoluciones ventas', 'M', '', 'TSBDevolucionesVentas', 'Devoluciones venas', '', 'DevolucionesVentas', 24)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(36, 25, 'TSMICreditos', 'Creditos', 'M','', 'TSBCreditos', 'Creditos', '', 'Creditos', 19)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(37, 25, 'TSMISeparador8', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(38, 25, 'TSMIDepositosBancarios', 'Depositos bancarios', 'M', '', 'TSBDepositosBancarios', 'Depositos bancarios', '', 'DepositosBancarios', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(39, 25, 'TSMISeparador9', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(40, 25, 'TSMIAsientosContables', 'Asientos contables', 'M', '', 'TSBAsientosContables', 'Asientos contables', '', 'AsientosContables', 26)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(41, 25, 'TSMISeparador10', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(42, 25, 'TSMITransferenciaProductos', 'Transaferencia de Productos', 'M', '', 'TSBTransferenciaProductos', 'Transferencia de Productos', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(43, NULL, 'TSMIHerramientas', 'Herramientas', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(44, 43, 'TSMIAdministradorCompras', 'Administrador de Compras', 'M', '', 'TSBAdministradorCompras', 'Administrador de Compras', '', 'AdministradorCompras', 41)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(45, 43, 'TSMIAdministradorVentas', 'Administrador de Ventas', 'M', '', 'TSBAdministradorVentas', 'Administrador de Ventas', '', 'AdministradorVentas', 40)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(46, 43, 'TSMIAdministradorInventarios', 'Administrador de inventarios', 'M', '', 'TSBAdministradorInventarios', 'Administrador de Inventarios', '', 'AdministradorInventarios', 7)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(47, 43, 'TSMIAdministradorTransferencias', 'Administrador de Transferencias', 'M', '', 'TSBAdministradorTransferencias', 'Administrador de Transferencias', '', 'AdministradorTransferencias', 46)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(48, 43, 'TSMIAdministradorRequerimientoProductos', 'Administrador de Requerimiento de Productos', 'M', '', 'TSBAdministradorRequerimientoProductos', 'Administrador de Requerimiento de Productos', '', 'AdministradorRequerimientoProductos', 25)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(49, 43, 'TSMIAdministradorContable', 'Administrador Contable', 'M', '', 'TSBAdministradorContable', 'Administrador Contable', '', 'AdministradorContable', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(50, 49, 'TSMIInicioGestion', 'Inicio de Gestión', 'M', '', 'TSBInicioGestion', 'Inicio de Gestión', '', 'InicioGestion', 33)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(51, 43, 'TSMIControlCaja', 'Control de Caja', 'M', '', 'TSBControlCaja', 'Control de Caja', '', 'ControlCaja', 28)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(52, 43, 'TSMISeparador11', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(53, 43, 'TSMICotizacionesVentas', 'Cotizaciones ventas', 'M', '', 'TSBCotizacionesVentas', 'Cotizaciones ventas', '', 'CotizacionesVentas', 3)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(54, 43, 'TSMIListadoProductosVentas', 'Listado de Productos Ventas', 'M', '', 'TSBListadoProductosVentas', 'Listado de Productos Ventas', '', 'ListadoProductosVentas', 42)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(55, 43, 'TSMISeparador12', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(56, 43, 'TSMISeguimientoCompetencia', 'Seguimiento a competencia', 'M', '', 'TSBSeguimientoCompetencia', 'Seguimiento a competencia', '', 'SeguimientoCompetencia', NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(57, 43, 'TSMISeparador13', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(58, 43, 'TSMIImportarListasProveedores', 'Importar listas proveedores', 'M', '', 'TSBImportarListasProveedores', 'Importar listas proveedores', '', 'ImportarListasProveedores', 37)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(59, NULL, 'TSMIReportes', 'Reportes', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(60, 59, 'TSMIReportesVentas', 'Reporte Ventas', 'M', '', NULL, '', '', 'VentasReporte', 39)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(61, 59, 'TSMISeparador14', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(62, 59, 'TSMIReportesCompras', 'Reportes Compras', 'M', '', NULL, '', '', 'ComprasReporte', 38)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(63, 59, 'TSMISeparador15', '-', 'S', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(64, 59, 'TSMIContabilidad', 'Contabilidad', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(65, 64, 'TSMIBalanceGeneral', 'Balance general', 'M', '', 'TSBBalanceGeneral', 'Balance general', '', 'BalanceGeneral',29)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(66, 64, 'TSMIEstadoResultados', 'Estado de resultados', 'M', '', 'TSBEstadoResultados', 'Estado resultados', '', 'EstadoResultados',31)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(67, 64, 'TSMILibroDiario', 'Libro diario', 'M', '', 'TSBLibroDiario', 'Libro diario', '', 'LibroDiario', 34)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(68, 64, 'TSMILibroMayores', 'Libro de mayores', 'M', '', 'TSBLibroMayores', 'Libro mayores', '', 'LibroMayores', 35)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(69, 64, 'TSMIBalanceGeneralComparativo', 'Balance General Comparativo', 'M', '', 'TSBBalanceGeneralComparativo', 'Balance General Comparativo', '', 'BalanceGeneralComparativo', 30)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(70, 64, 'TSMIEstadoResultadosComparativo', 'Estado Resultados Comparativo', 'M', '', 'TSBEstadoResultadosComparativo', 'Estado Resultados Comparativo', '', 'EstadoResultadosComparativo', 32)

INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(71, NULL, 'TSMIConfiguracion', 'Configuración', 'M', '', NULL, '', '', NULL,NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(72, 71, 'TSMIRegional', 'Regional', 'M', '', NULL, '', '', NULL,NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(73, 72, 'TSMIPaises', 'Paises', 'M', '', 'TSBPaises', 'Paises', '', 'Paises',6)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(74, 72, 'TSMIDepartamentos', 'Departamentos', 'M', '', 'TSBDepartamentos', 'Departamentos', '', 'Departamentos',6)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(75, 72, 'TSMIProvincias', 'Provincias', 'M', '', 'TSBProvincias', 'Provincias', '', 'Provincias',6)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(76, 72, 'TSMILugares', 'Lugares', 'M', '', 'TSBLugares', 'Lugares', '', 'Lugares',6)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(77, 71, 'TSMIProductosConfiguracion', 'Productos', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(78, 77, 'TSMIMarcas', 'Marcas', 'M', '', 'TSBMarcas', 'Marcas', '', 'Marcas', 12)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(79, 77, 'TSMIPropiedades', 'Propiedades', 'M', '', 'TSBPropiedades', 'Propiedades', '', 'Propiedades',13)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(80, 77, 'TSMITiposProductos', 'TiposProductos', 'M', '', 'TSBTiposProductos', 'Tipo productos', '', 'TiposProductos',14)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(81, 77, 'TSMIUnidades', 'Unidades', 'M', '', 'TSBUnidades', 'Unidades', '', 'Unidades',15)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(82, 71, 'TSMICuentasPorCobrarPagar', 'Cuentas por cobrar & pagar', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(83, 82, 'TSMIFrecuenciaPagos', 'Frecuencia pagos', 'M', '', 'TSBFrecuencia pagos', 'Frecuencia pagos', '', 'FrecuenciasPagos', 5)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(84, 71, 'TSMITransaccionesConfiguracion', 'Transacciones', 'M', '', NULL, '', '', NULL, NULL)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(85, 84, 'TSMIMonedasFracciones', 'Monedas Fracciones', 'M', '', NULL, '', '', 'MonedasFracciones', 36)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(86, 84, 'TSMIMotivosReemplazoDevolucion', 'Motivos reemplazo & devoluciones', 'M', '', 'TSBMotivosReemplazoDevolucion', 'MotivosReemplazoDevolucion', '', 'MotivosReemplazoDevolucion', 10)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(87, 84, 'TSMIBancos', 'Bancos', 'M', '', 'TSBBancos', 'Bancos', '', 'Bancos', 1)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(88, 84, 'TSMIMonedas', 'Monedas', 'M', '', 'TSBMonedas', 'Monedas', '', 'Monedas',8)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(89, 42, 'TSMITransferenciaProductosRegistro', 'Registro de Transferencias', 'M', '', 'TSBTransferenciaProductosRegistro', 'Registro de Transferencias', '', 'TransferenciaProductosRegistro',45)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(90, 42, 'TSMITransferenciaProductosGastos', 'Administración de Gastos Por Transfernecias', 'M', '', 'TSBTransferenciaProductosGastos', 'Administración de Gastos Por Transfernecias', '', 'TransferenciaProductosGastos',48)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(91, 42, 'TSMITransferenciasProductosRecepcion', 'Recepción de Transferencias', 'M', '', 'TSBTransferenciasProductosRecepcion', 'Recepción de Transferencias', '', 'TransferenciasProductosRecepcion',47)
INSERT INTO SistemaMenuPrincipal(CodigoElementoMenu, CodigoElementoMenuPadre, NombreElementoMenu, TextoElementoMenu, CodigoTipoElementoMenu, URLImagenElementoMenu, NombreBotonBarra, TextoBotonBarra, URLImagenBotonBarra, FuncionEnlace, CodigoInterface) VALUES(92, 42, 'TSMITransferenciasProductosEnvio', 'Envío de Transferencias', 'M', '', 'TSBTransferenciasProductosEnvio', 'Envío de Transferencias', '', 'TransferenciasProductosEnvio',47)
--'TransferenciaProductos' 42



INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 1, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 2, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 3, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 4, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 5, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 6, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 7, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 8, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 9, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 10, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 11, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 12, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 13, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 14, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 15, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 16, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 17, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 18, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 19, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 20, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 21, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 22, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 23, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 24, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 25, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 26, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 27, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 28, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 29, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 30, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 31, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 32, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 33, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 34, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 35, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 36, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 37, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 38, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 39, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 40, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 41, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 42, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 43, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 44, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 45, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 46, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 47, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 48, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 49, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 50, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 51, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 52, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 53, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 54, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 55, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 56, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 57, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 58, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 59, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 60, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 61, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 62, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 63, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 64, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 65, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 66, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 67, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 68, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 69, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 70, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 71, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 72, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 73, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 74, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 75, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 76, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 77, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 78, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 79, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 80, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 81, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 82, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 83, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 84, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 85, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 86, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 87, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 88, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 89, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 90, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 91, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 1, 92, 1, 1, 0)


INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 1, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 2, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 3, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 4, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 5, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 6, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 7, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 8, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 9, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 10, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 11, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 12, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 13, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 14, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 15, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 16, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 17, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 18, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 19, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 20, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 21, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 22, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 23, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 24, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 25, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 26, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 27, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 28, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 29, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 30, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 31, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 32, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 33, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 34, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 35, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 36, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 37, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 38, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 39, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 40, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 41, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 42, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 43, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 44, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 45, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 46, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 47, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 48, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 49, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 50, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 51, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 52, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 53, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 54, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 55, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 56, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 57, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 58, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 59, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 60, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 61, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 62, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 63, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 64, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 65, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 66, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 67, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 68, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 69, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 70, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 71, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 72, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 73, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 74, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 75, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 76, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 77, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 78, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 79, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 80, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 81, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 82, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 83, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 84, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 85, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 86, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 87, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 88, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 89, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 90, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 91, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 2, 92, 1, 1, 0)

INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 1, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 2, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 3, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 4, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 5, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 6, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 7, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 8, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 9, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 10, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 11, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 12, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 13, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 14, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 15, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 16, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 17, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 18, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 19, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 20, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 21, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 22, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 23, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 24, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 25, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 26, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 27, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 28, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 29, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 30, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 31, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 32, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 33, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 34, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 35, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 36, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 37, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 38, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 39, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 40, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 41, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 42, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 43, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 44, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 45, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 46, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 47, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 48, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 49, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 50, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 51, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 52, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 53, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 54, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 55, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 56, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 57, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 58, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 59, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 60, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 61, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 62, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 63, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 64, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 65, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 66, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 67, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 68, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 69, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 70, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 71, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 72, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 73, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 74, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 75, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 76, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 77, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 78, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 79, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 80, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 81, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 82, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 83, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 84, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 85, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 86, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 87, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 88, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 89, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 90, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 91, 1, 1, 0)
INSERT INTO UsuariosAgenciasMenuPrincipal(CodigoUsuario, NumeroAgencia, CodigoElementoMenu, Visible, Activo, IncluirBotonBarra) VALUES(1, 3, 92, 1, 1, 0)

