//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFADoblones20.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFADoblones20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap cart_add {
            get {
                object obj = ResourceManager.GetObject("cart_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cart_delete {
            get {
                object obj = ResourceManager.GetObject("cart_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cart_edit {
            get {
                object obj = ResourceManager.GetObject("cart_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cart_error {
            get {
                object obj = ResourceManager.GetObject("cart_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cart_go {
            get {
                object obj = ResourceManager.GetObject("cart_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraAceptar1 {
            get {
                object obj = ResourceManager.GetObject("CompraAceptar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraAnular {
            get {
                object obj = ResourceManager.GetObject("CompraAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraBuscar {
            get {
                object obj = ResourceManager.GetObject("CompraBuscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraCancelar1 {
            get {
                object obj = ResourceManager.GetObject("CompraCancelar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraFinalizar {
            get {
                object obj = ResourceManager.GetObject("CompraFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraFinalizar2 {
            get {
                object obj = ResourceManager.GetObject("CompraFinalizar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraModificarActualizar {
            get {
                object obj = ResourceManager.GetObject("CompraModificarActualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraNuevo {
            get {
                object obj = ResourceManager.GetObject("CompraNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompraNuevo2 {
            get {
                object obj = ResourceManager.GetObject("CompraNuevo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copia_de_Config {
            get {
                object obj = ResourceManager.GetObject("Copia de Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copia_de_Find {
            get {
                object obj = ResourceManager.GetObject("Copia de Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CotizacionNuevaDeOtra2 {
            get {
                object obj = ResourceManager.GetObject("CotizacionNuevaDeOtra2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompr {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompraAceptar {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompraAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompraAnular {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompraAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompraCancelar {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompraCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompraFinalizar {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompraFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionCompraNuevo {
            get {
                object obj = ResourceManager.GetObject("DevolucionCompraNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVenta {
            get {
                object obj = ResourceManager.GetObject("DevolucionVenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaAceptar {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaActualizar {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaActualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaAnular {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaCancelar {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaFinalizar {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevolucionVentaNuevo {
            get {
                object obj = ResourceManager.GetObject("DevolucionVentaNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emblem_sales {
            get {
                object obj = ResourceManager.GetObject("emblem_sales", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gtk_print_report {
            get {
                object obj = ResourceManager.GetObject("gtk_print_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVenta {
            get {
                object obj = ResourceManager.GetObject("IntercambioVenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVentaAceptar {
            get {
                object obj = ResourceManager.GetObject("IntercambioVentaAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVentaAnular {
            get {
                object obj = ResourceManager.GetObject("IntercambioVentaAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVentaCancelar {
            get {
                object obj = ResourceManager.GetObject("IntercambioVentaCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVentaFinalizar {
            get {
                object obj = ResourceManager.GetObject("IntercambioVentaFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IntercambioVentaNuevo {
            get {
                object obj = ResourceManager.GetObject("IntercambioVentaNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pagar {
            get {
                object obj = ResourceManager.GetObject("Pagar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioAceptar {
            get {
                object obj = ResourceManager.GetObject("ServicioAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioActualizarModificar {
            get {
                object obj = ResourceManager.GetObject("ServicioActualizarModificar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioAnular {
            get {
                object obj = ResourceManager.GetObject("ServicioAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioCancelar {
            get {
                object obj = ResourceManager.GetObject("ServicioCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioFinalizar {
            get {
                object obj = ResourceManager.GetObject("ServicioFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioNuevo {
            get {
                object obj = ResourceManager.GetObject("ServicioNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicioPagar {
            get {
                object obj = ResourceManager.GetObject("ServicioPagar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloAceptar {
            get {
                object obj = ResourceManager.GetObject("SimboloAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloActualizar {
            get {
                object obj = ResourceManager.GetObject("SimboloActualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloActualizar2 {
            get {
                object obj = ResourceManager.GetObject("SimboloActualizar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloAgregar {
            get {
                object obj = ResourceManager.GetObject("SimboloAgregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloAnular {
            get {
                object obj = ResourceManager.GetObject("SimboloAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloBuscar {
            get {
                object obj = ResourceManager.GetObject("SimboloBuscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloCancelar {
            get {
                object obj = ResourceManager.GetObject("SimboloCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloCerrar {
            get {
                object obj = ResourceManager.GetObject("SimboloCerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Simboloeditar {
            get {
                object obj = ResourceManager.GetObject("Simboloeditar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SimboloInterrogacion {
            get {
                object obj = ResourceManager.GetObject("SimboloInterrogacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaAceptar {
            get {
                object obj = ResourceManager.GetObject("TransferenciaAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaAnular {
            get {
                object obj = ResourceManager.GetObject("TransferenciaAnular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaBuscar {
            get {
                object obj = ResourceManager.GetObject("TransferenciaBuscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaCancelar {
            get {
                object obj = ResourceManager.GetObject("TransferenciaCancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaFinalizar {
            get {
                object obj = ResourceManager.GetObject("TransferenciaFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaModificar {
            get {
                object obj = ResourceManager.GetObject("TransferenciaModificar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferenciaNuevo {
            get {
                object obj = ResourceManager.GetObject("TransferenciaNuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaAceptar {
            get {
                object obj = ResourceManager.GetObject("VentaAceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaAceptar2 {
            get {
                object obj = ResourceManager.GetObject("VentaAceptar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaAnular3 {
            get {
                object obj = ResourceManager.GetObject("VentaAnular3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaCancelar2 {
            get {
                object obj = ResourceManager.GetObject("VentaCancelar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaCotizacion {
            get {
                object obj = ResourceManager.GetObject("VentaCotizacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaFinalizar {
            get {
                object obj = ResourceManager.GetObject("VentaFinalizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaModificar {
            get {
                object obj = ResourceManager.GetObject("VentaModificar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaNueva {
            get {
                object obj = ResourceManager.GetObject("VentaNueva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaNueva2 {
            get {
                object obj = ResourceManager.GetObject("VentaNueva2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaNuevaInstitucional {
            get {
                object obj = ResourceManager.GetObject("VentaNuevaInstitucional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentaReportes {
            get {
                object obj = ResourceManager.GetObject("VentaReportes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VentasBuscar {
            get {
                object obj = ResourceManager.GetObject("VentasBuscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VerEnOtraMoneda {
            get {
                object obj = ResourceManager.GetObject("VerEnOtraMoneda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
